import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Example data (replace these with your actual data)
labels = [
    "RekomendasiPantai",
    "balelabe",
    "barelang",
    "elyora",
    "fasilitasbalelabe",
    "fasilitaselyora",
    "fasilitasglorymelur",
    "fasilitasmirota",
    "fasilitasnongseabeach",
    "fasilitasnuvasa",
    "fasilitaspantaiapayung",
    "fasilitasreviola",
    "fasilitastanjungpinggir",
    "fasilitasviovio",
    "glorymelur",
    "greeting",
    "lokasibalelabe",
    "lokasielyora",
    "lokasiglorymelur",
    "lokasimirota",
    "lokasinongseabeach",
    "lokasinuvasa",
    "lokasipantaiapayung",
    "lokasireviola",
    "lokasitanjungpinggir",
    "lokasiwiovio",
    "mirota",
    "mongs",
    "nongseabeach",
    "nuvasa",
    "pantaiapayung",
    "reviola",
    "sekupang",
    "t1",
    "t2",
    "t3",
    "t4",
    "t5",
    "t6",
    "t7",
    "t8",
    "t9",
    "thanks",
    "tanjungpinggir",
    "viovio",
]
y_true = [
    "RekomendasiPantai",
    "balelabe",
    "barelang",
    "elyora",
    "fasilitasbalelabe",
    "fasilitaselyora",
    "fasilitasglorymelur",
    "fasilitasmirota",
    "fasilitasnongseabeach",
    "fasilitasnuvasa",
    "fasilitaspantaiapayung",
    "fasilitasreviola",
    "fasilitastanjungpinggir",
    "fasilitasviovio",
    "glorymelur",
    "greeting",
    "lokasibalelabe",
    "lokasielyora",
    "lokasiglorymelur",
    "lokasimirota",
    "lokasinongseabeach",
    "lokasinuvasa",
    "lokasipantaiapayung",
    "lokasireviola",
    "lokasitanjungpinggir",
    "lokasiwiovio",
    "mirota",
    "mongs",
    "nongseabeach",
    "nuvasa",
    "pantaiapayung",
    "reviola",
    "sekupang",
    "t1",
    "t2",
    "t3",
    "t4",
    "t5",
    "t6",
    "t7",
    "t8",
    "t9",
    "thanks",
    "tanjungpinggir",
    "viovio",
]
y_pred = [
    "RekomendasiPantai",
    "balelabe",
    "barelang",
    "elyora",
    "fasilitasbalelabe",
    "fasilitaselyora",
    "fasilitasglorymelur",
    "fasilitasmirota",
    "fasilitasnongseabeach",
    "fasilitasnuvasa",
    "fasilitaspantaiapayung",
    "fasilitasreviola",
    "fasilitastanjungpinggir",
    "fasilitasviovio",
    "glorymelur",
    "greeting",
    "lokasibalelabe",
    "lokasielyora",
    "lokasiglorymelur",
    "lokasimirota",
    "lokasinongseabeach",
    "lokasinuvasa",
    "lokasipantaiapayung",
    "lokasireviola",
    "lokasitanjungpinggir",
    "lokasiwiovio",
    "mirota",
    "mongs",
    "nongseabeach",
    "nuvasa",
    "pantaiapayung",
    "reviola",
    "sekupang",
    "t1",
    "t2",
    "t3",
    "t4",
    "t5",
    "t6",
    "t7",
    "t8",
    "t9",
    "thanks",
    "tanjungpinggir",
    "viovio",
]

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred, labels=labels)

# Convert to percentages
cm_percentage = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis] * 100

# Plot confusion matrix
plt.figure(figsize=(20, 15))  # Adjust size to accommodate larger number of labels
sns.heatmap(
    cm_percentage,
    annot=True,
    fmt=".2f",
    cmap="Blues",
    cbar=True,
    xticklabels=labels,
    yticklabels=labels,
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix in Percentages")
plt.xticks(rotation=90)  # Rotate x-axis labels for better readability
plt.yticks(rotation=0)  # Keep y-axis labels horizontal
plt.show()
